image: ubuntu:16.04

stages:
  - build

building:
  stage: build
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - make
  artifacts:
    name: vpa
    paths:
     - vpa
