name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: update
        run: sudo apt-get update -q -y
      - name: install
        run: sudo apt-get install -y build-essential
      - name: make
        run: make
