name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu:16.04
    steps:
      - uses: actions/checkout@master
      - name: make
        run:
          - apt-get update -q -y
          - apt-get install -y build-essential
          - make
