name: "release"

on:
  push:
    branches: [ "master" ]
    #tags:
    #  - "v*"

jobs:
  tagged-release:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: sudo apt-get update -y -q
      - run: sudo apt-get install -y build-essential upx
      - run: snap install zig --beta --classic
      - run: make zig
      - run: upx --lzma --best zig-out/bin/vpa
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: zig-out/bin/vpa
